# Question : Bus Count Index Retrieval
# Create a Python function named get_bus_indexes that takes the dataset-1.csv as a DataFrame. 
The function should identify and return the indices as a list (sorted in ascending order) where the bus values are greater than twice the mean value of the bus column in the DataFrame.

In [61]:
 import pandas as pd

get_bus_indexes= pd.read_csv("C:\\Users\\VINIT SANDESH\\Desktop\\DATA ANALYTICS\\PYTHON\\PROJECT DATASETS\\TRAVEL AGENCY.csv")
get_bus_indexes

     id_1  id_2  route   moto    car     rv   bus  truck
0     829   827      1   2.05   4.14   4.14  10.1   15.2
1     829   821      4   6.63  13.26  13.26  32.4   48.5
2     829   804      7  14.41  28.92  28.92  64.7   97.0
3     829   822      6   5.90  11.81  11.81  28.8   43.2
4     829   826      9   2.87   5.81   5.81  14.2   21.2
..    ...   ...    ...    ...    ...    ...   ...    ...
336   803   802      3   1.70   3.40   3.40   6.9   10.3
337   803   805      4   3.00   6.00   6.00  12.0   17.9
338   803   825      3  11.59  23.28  23.28  50.1   75.2
339   803   806      9   3.80   7.70   7.70  15.3   23.0
340   803   830      1  16.18  32.47  32.47  72.6  108.8

[341 rows x 8 columns]

In [45]:
get_bus_indexes.shape

(341, 8)

In [26]:
mean_bus_value1 = get_bus_indexes.bus.mean()
print("mean_bus_value Output: ", mean_bus_value)

mean_bus_value Output:  31.932844574780056

In [46]:
bus_index 1 = get_bus_indexes[get_bus_indexes['bus'] > 2 * mean_bus_value]
bus_index

     id_1  id_2  route   moto    car     rv   bus  truck
2     829   804      7  14.41  28.92  28.92  64.7   97.0
7     829   801      1  18.21  36.32  36.32  79.5  119.2
12    829   802      5  16.91  33.72  33.72  74.3  111.4
17    829   803      2  15.21  30.52  30.52  67.9  101.8
25    827   801      9  16.32  32.53  32.53  70.2  105.3
30    827   802      4  15.02  29.93  29.93  65.0   97.5
54    804   829     10  14.41  28.92  28.92  64.7   97.0
64    804   831      3  15.87  31.84  31.84  71.7  107.6
70    804   830      8  15.38  30.87  30.87  69.4  104.0
97    826   801      4  15.48  30.87  30.87  66.1   99.2
144   801   829      8  18.21  36.32  36.32  79.5  119.2
145   801   827      3  16.32  32.53  32.53  70.2  105.3
149   801   826      1  15.48  30.87  30.87  66.1   99.2
154   801   831      4  19.67  39.24  39.24  86.5  129.8
160   801   830      9  19.18  38.27  38.27  84.2  126.2
201   831   804      9  15.87  31.84  31.84  71.7  107.6
206   831   801      2  19.67  39.24  39.24  86.5  129.8
210   831   802      7  18.37  36.64  36.64  81.3  122.0
215   831   803      6  16.67  33.44  33.44  74.9  112.4
234   802   829      9  16.91  33.72  33.72  74.3  111.4
235   802   827      7  15.02  29.93  29.93  65.0   97.5
245   802   831      1  18.37  36.64  36.64  81.3  122.0
250   802   830      3  17.88  35.67  35.67  79.0  118.4
309   830   804      9  15.38  30.87  30.87  69.4  104.0
314   830   801      9  19.18  38.27  30.27  84.2  126.2
319   830   802      8  17.88  35.67  35.67  79.0  118.4
322   830   803      7  16.18  32.47  32.47  72.6  108.8
323   803   829     10  15.21  30.52  30.52  67.9  101.8
334   803   831      3  16.67  33.44  33.44  74.9  112.4
340   803   830      1  16.18  32.47  32.47  72.6  108.8

In [50]:
bus_index2 = get_bus_indexes[get_bus_indexes['bus'] > 2 * mean_bus_value].index
bus_index2

Index([  2,   7,  12,  17,  25,  30,  54,  64,  70,  97, 144, 145, 149, 154,
       160, 201, 206, 210, 215, 234, 235, 245, 250, 309, 314, 319, 322, 323,
       334, 340],
      dtype='int64')

In [57]:
sorted_in_ascending_order = bus_index.sort
sorted_in_ascending_order

<bound method Index.sort of Index([  2,   7,  12,  17,  25,  30,  54,  64,  70,  97, 144, 145, 149, 154,
       160, 201, 206, 210, 215, 234, 235, 245, 250, 309, 314, 319, 322, 323,
       334, 340],
      dtype='int64')>